config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resources :posts do
    resources :comments do
      member { post :vote }
    end
    member { post :vote }
  end

  get 'application/welcome'
  root 'application#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 100 }

  belongs_to :user
  belongs_to :post

  has_reputation :votes, source: :user, aggregated_by: :sum
  has_ancestry
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  before_validation :generate_slug

  validates :title, presence: true, length: { maximum: 10 }
  validates :content, presence: true, length: { maximum: 200 }
  validates :slug, uniqueness: true, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy

  mount_uploader :image, PostImageUploader

  has_reputation :votes, source: :user, aggregated_by: :sum

  def to_param
    slug
  end

  def generate_slug
    self.slug ||= title.parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 10 },
                   uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :set_visitor_cookie
  def welcome
    redirect_to posts_url if current_user
  end

  def set_visitor_cookie
    cookies[:visits] = {
      value: increment_counter,
      expires: 1.year.from_now
    }
  end

  def increment_counter
    @pageviews = cookies[:visits].to_i
    if @pageviews.nil? || !user_signed_in?
      @pageviews = 0
    else
      @pageviews += 1
    end
  end

  def track_visits
    @pageviews -= 1
  end

  helper_method :track_visits

  def set_date(post)
    Russian.strftime(post.created_at, ' Запись создана: %d %B %Y года в %H:%M')
  end

  helper_method :set_date
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.find_by_slug!(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    @comment.save

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def destroy
    @post = Post.find_by_slug!(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to @post }
      format.js
    end
  end

  def new
    @post = Post.find_by_slug!(params[:post_id])
    @comment = @post.comments.new(parent_id: params[:parent_id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def vote
    @post = Post.find_by_slug!(params[:post_id])
    @comment = @post.comments.find(params[:id])
    value = params[:type] == 'up' ? 1 : -1
    @comment.add_or_update_evaluation(:votes, value, current_user)
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:parent_id, :body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_filter :verify_authenticity_token, only: :create
  before_action :set_post, only: [:show, :edit, :update, :destroy, :vote]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.includes(:user)
    respond_to do |format|
      format.html
      format.json do
        render json: @posts,
               except: [:updated_at, :user_id],
               include: { user: { only: [:name] } }
      end
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments
    respond_to do |format|
      format.html
      format.json do
        render json: @posts,
               except: [:updated_at, :user_id],
               include: { user: { only: [:name] } }
      end
    end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html do
          redirect_to @post,
                      notice: 'Post was successfully created.'
        end
        format.json do render :show,
                              status: :created,
                              location: @post
        end
        format.js
      else
        format.html { render :new }
        format.json do
          render json: @post.errors,
                 status: :unprocessable_entity
        end
        format.js
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html do
          redirect_to @post,
                      notice: 'Post was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json do
          render json: @post.errors,
                 status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html do
        redirect_to posts_url,
                    notice: 'Post was successfully destroyed.'
      end
      format.json { head :no_content }
      format.js
    end
  end

  def vote
    value = params[:type] == 'up' ? 1 : -1
    @post.add_or_update_evaluation(:votes, value, current_user)
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find_by_slug!(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :content, :image)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email,
                                 :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email,
                                 :password, :password_confirmation,
                                 :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div,
                                    nested_comments(sub_comments),
                                    class: 'nested_comments')
    end.join.html_safe
  end
end

app/views/application/welcome.html.erb
<div id='doors'>
  <h1>Добро пожаловать в</h1>
  <div id="welcome_logo"></div>
  <%= link_to "Войти", new_user_session_path, class: "btn btn-success", id:'button_in' %>
</div>

app/views/comments/_comment.html.erb
<li id="comment_<%= comment.id %>">
  <div class="side"></div>
  <div class = "comment_body">
    <strong><%= comment.user.name %></strong>
    <span class='date'>     <%= time_ago_in_words(comment.created_at) %> назад </span>
    <span class='right_action' >
      <span id="comment_<%= comment.id %>_count">
        <%= pluralize comment.reputation_for(:votes).to_i, "vote" %>
      </span>
      <%= link_to '', vote_post_comment_path(@post, comment, type: 'up'), method: 'post', remote: true, class:'glyphicon glyphicon-thumbs-up' %>
      <%= link_to '', vote_post_comment_path(@post, comment, type: 'down'), method: 'post', remote: true, class:'glyphicon glyphicon-thumbs-down' %>

      <% if @post.user == current_user || comment.user == current_user%>
          <%= link_to '', [comment.post, comment],
                      method: :delete,
                      remote: true,
                      class: 'glyphicon glyphicon-remove',
                      data: { confirm: 'Are you shure?' } %>
      <% end %> <br>
      <%= link_to "", new_post_comment_path(@post, parent_id: comment), remote: true, class:'glyphicon glyphicon-chevron-down' %>
    </span>
    <p>
      <%= comment.body %>
    </p>
  </div>
</li>

app/views/comments/create.js.erb
if ('<%= @comment.parent_id %>') {
  $('#comment_<%= @comment.parent_id %>').next('.nested_comments').append("<%= j render @comment %>");
  $('#comment_<%= @comment.parent_id %>').next('.nested_comments').append("<div class='nested_comments'></div>");
}else {
  $('.comments').append("<%= j render @comment %>");
  $('.count_comments_post_<%= @post.id %>').text("<%= @post.comments.count %>");
    $('.comments').append("<div class='nested_comments'></div>");
};

$('.form-control').val('');
$('#comment_<%= @comment.parent_id %>').next('.nested_comments').next().remove();

app/views/comments/destroy.js.erb
$('.comments').find('#comment_<%= @comment.id %>').next().remove();
$('.comments').find('#comment_<%= @comment.id %>').remove();
$('.count_comments_post_<%= @post.id %>').text("<%= @post.comments.count %>");

app/views/comments/new.js.erb
if ($('#comment_<%= @comment.parent_id %>').next('.nested_comments').next('form').length > 0){
  $('.comments').find('form').remove();
} else {
  $('.comments').find('form').remove();
  $('#comment_<%= @comment.parent_id %>').next('.nested_comments').after('<%= j render 'posts/form_for_comment', post: @comment  %>');
}

app/views/comments/vote.js.erb
$('#comment_<%= @comment.id %>_count').text('<%= pluralize @comment.reputation_for(:votes).to_i, "vote" %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="downlited">
  <header class="navbar navbar-fixed-top navbar-inverse" id="header_style">
    <div class="container">
      <%= link_to image_tag('logo-exsm.png', alt: "blog-logo"), root_path, id: "logo"%>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <% if !user_signed_in? %>
            <li><%= link_to "Регистрация", new_user_registration_path %></li>
            <li><%= link_to "Войти", new_user_session_path %></li>
          <% else %>
            <li><%= link_to "Выйти", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
  <div class="container", id="style_for_body">
    <div class= 'views' data-vies="<%= track_visits %>">
      <% if track_visits % 10 == 0 %>
        <%= render 'baner' %>
      <% end %>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/_baner.html.erb
<div class='background'></div>
<div class= 'baner' >
  <h1>Ты можешь изменить мир!</h1>
  <h2>Только верь в себя.</h2>
  <button type='button' class='btn btn-success btnsd'>Спасибо!</button>
</div>

app/views/posts/_commentsblock.html.erb
<section class="comment-section">
  <ul class="comments">
    <%= nested_comments @comments.arrange(order: :created_at) %>
  </ul>.
  <%= render 'form_for_comment' %>
</section>

app/views/posts/_form.html.erb
<%= form_for(post, remote:true)  do|f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title, "Тема:" %>
    <%= f.text_field :title, class: "form-control form-width" %>
  </div>
  <div class="field form-group">
    <%= f.label :image, "Катинка:" %>
    <%= f.file_field :image %>
  </div>
  <div class="field form-group">
    <%= f.label :content, "Высказывание:"%>
    <%= f.text_area :content, class: "form-control form-width", rows:"3" %>
  </div>

  <div class="actions button-margin">
    <%= f.submit "Сказать" , class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/_form_for_comment.html.erb
<%= form_for [@post, @post.comments.new(parent_id: params[:parent_id])], remote: true do|f| %>
    <fieldset>
      <ul>
        <%= f.hidden_field :parent_id %>
        <li>
          <%= f.text_area :body, class:'form-control', rows: 2, cols: 60,
                          placeholder: 'Дайте комментарий...' %>
        </li>
        <li class="button_margin_comment">
          <%= f.submit 'Прокомментировать', class: "btn btn-success btn-sm" %>
        </li>
      </ul>
    </fieldset>
<% end %>

app/views/posts/_post.html.erb
<% @post = post %>
<% @comments = post.comments %>
<tr class="post_<%= post.id %>">
  <td rowspan="2" class='small_logo' >
    <% if post.image? %>
        <%= link_to image_tag(post.image_url(:thumb), alt: "Post logo"), post%>
    <% else %>
        <%=  link_to image_tag('defaultimage_sm.jpg', alt: "Post logo"), post%>
    <% end %>
  </td>
  <td class="broun_row"><strong>Автор:</strong><%= post.user.name%>
    <span class='right_action' >
      <%= link_to '', post, class: "glyphicon glyphicon-share-alt" %>
      <% if post.user == current_user %>
        <%= link_to '', edit_post_path(post), class: "glyphicon glyphicon-pencil" %>
        <%= link_to '', post, method: :delete, remote: true,  class: "glyphicon glyphicon-remove", data: { confirm: 'Are you sure?'} %>
      <% end %>
    </span>
  </td>
</tr>
<tr class="yellow_row post_<%= post.id %>">
  <td ><strong>Тема:</strong> <%= post.title %><span class='right_action' ><%= set_date(post) %></span></td>
</tr>
<tr class="active post_<%= post.id %>">
  <td colspan="2"><%= post.content %>
    <span class='right_action' >
      <span class="count_vote_post_<%= post.id %>">
        <span id="post_<%= post.id %>_count"><%= pluralize post.reputation_for(:votes).to_i, "vote" %></span>
        <%= link_to '', vote_post_path(post, type: 'up'),method: 'post', remote: true, class:'glyphicon glyphicon-thumbs-up' %>
        <%= link_to '', vote_post_path(post, type: 'down'),method: 'post', remote: true, class:'glyphicon glyphicon-thumbs-down' %>
      </span>
      <button type='button' class='comments-link glyphicon glyphicon-comment '></button>
      <span class="count_comments_post_<%= post.id %>"><%= post.comments.count %></span>
    </span>
  </td>
</tr>
<tr class="row-comments borders post_<%= post.id %>">
  <td colspan="2">
    <span class='right_action', id="block_id_<%= post.id %>">
      <%= render 'commentsblock' %>
    </span>
  </td>
</tr>

app/views/posts/create.js.erb
if( $('.table').find('tr').length == 0 ){
  $('h2').remove();
  $('.table').append("<tr></tr>");
};
$('.table').find('tr').last().after('<%= j render @post %>')
$('#new_post').find('input').val('');
$('#new_post').find('textarea').val('');

app/views/posts/destroy.js.erb
$('table').find('.post_<%= @post.id %>').remove();
//if()
//$('.table').append('<h2>Никто ничего не сказал.</h2>');
//$('.table').append("<tr></tr>");

app/views/posts/edit.html.erb
<% provide(:title, "Поправить себя") %>
<span id="edit"></span>
<div class="background-show">
  <p class="messages">
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span></p>

  <h1>Поправить себя</h1>

  <% if user_signed_in? && @post.user == current_user  %>
    <%= render 'form', post: @post %>
  <% else %>
    <h2> Вы не можете поправить высказывание другого человека</h2>
  <% end %>
  <%= link_to 'Назад', posts_path, class: "btn btn-default btn-xs"  %>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Высказывания") %>
<span id="index"></span>
<div class="background-show">
<p class="messages">
  <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span></p>

<h1>Высказывания</h1>


<table class="table">
  <% if @posts.count == 0 %>
    <h2>Никто ничего не сказал.</h2>
  <% else %>
    <%= render @posts %>
  <% end %>
</table>

<br>
<%= link_to 'Высказаться', new_post_path, remote: true, id:"new_post_link", class: "btn btn-success"  %>
</div>

app/views/posts/new.html.erb
<% provide(:title, "Высказаться") %>
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Назад', posts_path, class: "btn btn-default btn-xs" %>

app/views/posts/new.js.erb
if ($('#new_post_link').next('form').length > 0) {
  $('#new_post_link').next().remove();
} else {
  $('#new_post_link').after('<%= j render 'form', post: @post  %>');
};

app/views/posts/show.html.erb
<% provide(:title, "Высказывание") %>
<span id="show"></span>
<div class="background-show">
  <p class="messages">
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span></p>

  <h2><%= @post.user.name %>высказался</h2>
  <div class="container container_post">
  <% if @post.image? %>
    <%= image_tag @post.image_url , class:'image_logo'%>
  <% else %>
    <%= image_tag 'defaultimage.jpg' , class:'image_logo'%>
  <% end %>
  <span class='right_action votes' > <%= set_date(@post) %><br>
    <span class="count_vote_post_<%= @post.id %>" >
          <span id="post_<%= @post.id %>_count"><%= pluralize @post.reputation_for(:votes).to_i, "vote" %></span>
      <%= link_to '', vote_post_path(@post, type: 'up'),method: 'post', remote: true, class:'glyphicon glyphicon-thumbs-up' %>
      <%= link_to '', vote_post_path(@post, type: 'down'),method: 'post', remote: true, class:'glyphicon glyphicon-thumbs-down' %>
    </span>
  </span>
  <h3 id="title_show"><strong>Тема:</strong> <%= @post.title %></h3>
  <div class='content'>
    <h4><strong>Высказывание:</strong></h4>
    <p><%= @post.content %></p>
  </div>
  </div>
  <span  id="block_id_<%= @post.id %>">
  <%= render 'commentsblock' %>
  </span>
  <div class = "show_action">
  <% if user_signed_in? && @post.user == current_user  %>
    <%= link_to 'Поправить', edit_post_path(@post), class: "btn btn-warning" %>
  <% end %>
  <%= link_to 'Назад', posts_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/posts/vote.js.erb
$('#post_<%= @post.id %>_count').text('<%= pluralize @post.reputation_for(:votes).to_i, "vote" %>');